### ISSUE TITLE
Line height

### ISSUE THREAD

**Issue by JupiterThreads** [skaran921/flutter_shimmer#10]
I like your package. Is there anyway to increase the shimmer line height in say the ListTileShimmer widget? It would also be good to accept a dynamic height for the leading and trailing widgets. Thanks

**Comment by skaran921** [comment]
Thank you so much @JupiterThreads for your feedback. i will surely added this option in next version.

**Comment by skaran921** [comment]
Hi @JupiterThreads  Now you can use height property  of ListTileShimmerWidget to increase height.
example:  
ListTileShimmer(
            height: 20,
),
