### ISSUE TITLE
Loading only on avatar photo

### ISSUE THREAD

**Issue by fabioselau077** [skaran921/flutter_shimmer#12]
Hi, is it possible to make this animation but only on a circleavatar, without having any text?
Because the most I saw was ProfileShimmer and ProfilePageShimmer but both besides the profile picture still make text animation, I only need the 'CircleAvatar'.
Can you do it?

**Comment by skaran921** [comment]
Hi! first of all, thank you for raising this issue i am looking on it. Can you share the screenshots for the same?

**Comment by skaran921** [comment]
@fabioselau077  please have a look on  screenshot. is it  fine ?
![Screenshot_1623152132](https://user-images.githubusercontent.com/34412777/121178665-658a6280-c87c-11eb-9b26-e203956c675d.png)

**Comment by skaran921** [comment]
fixed
