### ISSUE TITLE
Suggestion to add a background color as option.

### ISSUE THREAD

**Issue by syedecryptr** [skaran921/flutter_shimmer#15]
hello, you've made an awesome widget!. I think it will be better to add properties background color because some people might need it. Thanks
Currently it's hardcoded here : 

`color: widget.isDarkMode ? Color(0xFF0B0B0B) : Colors.transparent,`

**Comment by skaran921** [comment]
Hi @syedecryptr  thanks for your suggestion I will update you soon for the same.

**Comment by skaran921** [comment]
Hi @syedecryptr   I just uploaded new version 2.1.2 on pub.dev now you can change the background color by using bgColor property. 

Demo code :  
                             ListTileShimmer(
                                bgColor: Colors.yellow,
                                onlyShowProfilePicture: true,
                                height: 20,                           
                              ),

Output: 
![image](https://user-images.githubusercontent.com/34412777/134498334-83922b4c-a24a-4fbc-9b12-0011efa025ce.png)

hope you like it.
