### ISSUE TITLE
Suggestion : add an option to disable profile / rect box

### ISSUE THREAD

**Issue by rizaldyaf** [skaran921/flutter_shimmer#6]

**Comment by skaran921** [comment]
thanks @rizaldyaf  for your suggestion. i will work on your issue but can you describe me little bit more about your issue it will helpful for me.
i am waiting for your replay.
thanks in advance

**Comment by rizaldyaf** [comment]
hello, you've made an awesome widget!. I think it will be better to add properties on ListTileShimmer like disableAvatar : true / false, because some people might not needed it. Thanks

**Comment by skaran921** [comment]
Okay, i got it. i have fix this issue as soon as possible after fix this issue i will inform you. 
please hit the star button if you like this repository .
thank u so much for your suggestion.

**Comment by skaran921** [comment]
hi @rizaldyaf  i have fix the issue now you can use isDisabledAvatar: true to disable profile / rect box
check the new version : https://pub.dev/packages/flutter_shimmer/versions/1.2.0.
😊😊😊👍👍👍
